### PR TITLE
Disqus comment count bug fixes

### PR DESCRIPTION
**Pull request by pupboss**

### CODE REVIEW

**Comment by kelyvin** [comment]
Thanks for the fix and great catch!

**Comment by pupboss** [comment]
Hmm, pls don't merge it immediately.

I found that it may cause problems, in some country, such as China, Disqus was banned, so even though the count.js was loaded via async, it still block the rendering, until count.js was time out, I'm not a front-end programer...So I didn't get any way out, I hope you can do it at your convenience : )

**Comment by kelyvin** [comment]
That's okay I have merged the change in anyway, since the app supports disqus by default it's an easy add. Even If disqus does not exist, the url route change is only a "hash fragment". So if the disqus comments don't exist, it won't affect scrolling on the page anyway. :)

**Comment by pupboss** [comment]
It seems we had a little miscommunication, I'll put on an image to clarify

The script looks like this:

`<script id="dsq-count-scr" src="//pupboss.disqus.com/count.js" async></script>`

But if I don't turn on the proxy, count.js can not be loaded because the Chinese GOV banned the Disqus.



While the loading of count.js, the rendering of the page also blocked.



I didn't know why the async loading of a .js would block the page rendering...

**Comment by pupboss** [comment]
Oh! I see!!

Maybe the masonry's layout action needed all resources was loaded, so the count.js blocked the layout action. I'll try to fix it.

**Pull request closed without merging**
